language: python
dist: xenial
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9-dev"
before_install:
  - sudo add-apt-repository -y ppa:phoerious/keepassxc
  - sudo apt-get -q update
  - sudo apt-get -y install keepassxc
  - pip install -r requirements-dev.txt
install:
  - python3 setup.py install
addons:
  apt:
    update: true
script:
 - mypy keepassxc_pwned
 - pytest

