language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - git clone https://github.com/keepassxreboot/keepassxc
  - cd ./keepassxc
  - ./release-tool build --version 2.5.4
  - pip install -r requirements-dev.txt
install:
  - python3 setup.py install
addons:
  apt:
    update: true
script:
 - mypy keepassxc_pwned
 - pytest --cov-report term --cov=keepassxc_pwned tests/
after_success:
 - codecov

