language: python
dist: xenial
python:
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - sudo add-apt-repository -y ppa:phoerious/keepassxc
  - sudo apt-get -q update
  - sudo apt-get -y install keepassxc
  - pip install pexpect pytest
install:
  - python3 setup.py install
addons:
  apt:
    update: true
script:
 - pytest

